<?php

$articles = [
    ["title" => "Voiture 1", "content" => "PHP Lorem ipsum dolor sit amet consectetur adipisicing elit. Ducimus quidem labore rerum quod quis qui, aut, ut distinctio aperiam quae ipsa beatae hic inventore vero et ad itaque totam voluptatibus.", "images" => "Voiture 2.jpg"],
    ["title" => "Voiture 2", "content" => "React Lorem ipsum dolor sit amet consectetur adipisicing elit. Ducimus quidem labore rerum quod quis qui, aut, ut distinctio aperiam quae ipsa beatae hic inventore vero et ad itaque totam voluptatibus.", "images" => "assets/images/voiture 1.png"],
    ["title" => "Voiture 3", "content" => "React Lorem ipsum dolor sit amet consectetur adipisicing elit. Ducimus quidem labore rerum quod quis qui, aut, ut distinctio aperiam quae ipsa beatae hic inventore vero et ad itaque totam voluptatibus.", "images" => "2-react-vs-react-native.jpg"],
    ["title" => "Voiture 4", "content" => "React Lorem ipsum dolor sit amet consectetur adipisicing elit. Ducimus quidem labore rerum quod quis qui, aut, ut distinctio aperiam quae ipsa beatae hic inventore vero et ad itaque totam voluptatibus.", "images" => "2-react-vs-react-native.jpg"],
    ["title" => "Voiture 5", "content" => "React Lorem ipsum dolor sit amet consectetur adipisicing elit. Ducimus quidem labore rerum quod quis qui, aut, ut distinctio aperiam quae ipsa beatae hic inventore vero et ad itaque totam voluptatibus.", "images" => "2-react-vs-react-native.jpg"],
    ["title" => "Voiture 6", "content" => "React Lorem ipsum dolor sit amet consectetur adipisicing elit. Ducimus quidem labore rerum quod quis qui, aut, ut distinctio aperiam quae ipsa beatae hic inventore vero et ad itaque totam voluptatibus.", "images" => "2-react-vs-react-native.jpg"],
    ["title" => "Voiture 7", "content" => "React Lorem ipsum dolor sit amet consectetur adipisicing elit. Ducimus quidem labore rerum quod quis qui, aut, ut distinctio aperiam quae ipsa beatae hic inventore vero et ad itaque totam voluptatibus.", "images" => "2-react-vs-react-native.jpg"],
    ["title" => "Voiture 8", "content" => "React Lorem ipsum dolor sit amet consectetur adipisicing elit. Ducimus quidem labore rerum quod quis qui, aut, ut distinctio aperiam quae ipsa beatae hic inventore vero et ad itaque totam voluptatibus.", "images" => "2-react-vs-react-native.jpg"],
    ["title" => "Voiture 9", "content" => "React Lorem ipsum dolor sit amet consectetur adipisicing elit. Ducimus quidem labore rerum quod quis qui, aut, ut distinctio aperiam quae ipsa beatae hic inventore vero et ad itaque totam voluptatibus.", "images" => "2-react-vs-react-native.jpg"],
    ["title" => "Voiture 10", "content" => "React Lorem ipsum dolor sit amet consectetur adipisicing elit. Ducimus quidem labore rerum quod quis qui, aut, ut distinctio aperiam quae ipsa beatae hic inventore vero et ad itaque totam voluptatibus.", "images" => "2-react-vs-react-native.jpg"],
    ["title" => "Voiture 11", "content" => "Devops Lorem ipsum dolor sit amet consectetur adipisicing elit. Ducimus quidem labore rerum quod quis qui, aut, ut distinctio aperiam quae ipsa beatae hic inventore vero et ad itaque totam voluptatibus.", "images" => "Voiture 2.jpg"],
];
